# Generated by Django 5.0.7 on 2024-07-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
    ]
