# Generated by Django 5.0.7 on 2024-07-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0002_review_delete_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='actors',
            new_name='actor',
        ),
    ]
