# Generated by Django 5.0.7 on 2024-07-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtool_posts', '0001_initial'),
        ('idea_posts', '0002_rename_photo_ideapost_image_remove_ideapost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtoolpost',
            name='ideas',
            field=models.ManyToManyField(related_name='related_devtools', to='idea_posts.ideapost'),
        ),
        migrations.AlterField(
            model_name='devtoolpost',
            name='kind',
            field=models.CharField(max_length=30),
        ),
    ]
