# Generated by Django 5.0.7 on 2024-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtool_posts', '0002_devtoolpost_ideas_alter_devtoolpost_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtoolpost',
            name='kind',
            field=models.CharField(max_length=30, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='devtoolpost',
            name='name',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
    ]
