# Generated by Django 5.0.7 on 2024-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideapost',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='ideapost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ideapost',
            name='region',
        ),
        migrations.AddField(
            model_name='ideapost',
            name='devtool',
            field=models.CharField(choices=[(' ', '-------'), ('Django', '장고'), ('React', '리액트'), ('Spring', '스프링'), ('Node.js', '노드'), ('Java', '자바'), ('C++', '시쁠쁠'), ('Etc', '기타')], max_length=20, null=True, verbose_name='개발툴'),
        ),
        migrations.AddField(
            model_name='ideapost',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='관심도'),
        ),
        migrations.AlterField(
            model_name='ideapost',
            name='content',
            field=models.TextField(max_length=100, verbose_name='아이디어 설명'),
        ),
        migrations.AlterField(
            model_name='ideapost',
            name='title',
            field=models.CharField(max_length=50, verbose_name='아이디어명'),
        ),
    ]
