# Generated by Django 5.0.7 on 2024-07-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtool_posts', '0002_devtoolpost_ideas_alter_devtoolpost_kind'),
        ('idea_posts', '0002_rename_photo_ideapost_image_remove_ideapost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideapost',
            name='devtool',
        ),
        migrations.AddField(
            model_name='ideapost',
            name='devtools',
            field=models.ManyToManyField(related_name='related_ideas', to='devtool_posts.devtoolpost'),
        ),
    ]
