# Generated by Django 5.0.7 on 2024-07-17 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtool_posts', '0003_alter_devtoolpost_kind_alter_devtoolpost_name'),
        ('idea_posts', '0003_remove_ideapost_devtool_ideapost_devtools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideapost',
            name='devtools',
        ),
        migrations.AddField(
            model_name='ideapost',
            name='devtools',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_ideas', to='devtool_posts.devtoolpost'),
        ),
    ]
