# Generated by Django 5.0.7 on 2024-07-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_posts', '0004_remove_ideapost_devtools_ideapost_devtools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideapost',
            old_name='devtools',
            new_name='devtools_id',
        ),
    ]
